[package]
name = "rust_csv_cli"
version = "1.0.2"
edition = "2024"

[dependencies]
csv = "1.2"
clap  = { version = "4.5", features = ["derive"] }
anyhow = "1.0"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
tempfile = "3.8"
