name: Rust CSV CLI CI

on:
  push:
    branches: ["main"]
    tags-ignore: ["v*"]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy

      - name: Build
        run: cargo build --verbose

      - name: Unit & Integration Tests
        run: cargo test --verbose

      - name: Clippy (deny warnings)
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: rustfmt (check)
        run: cargo fmt --all -- --check
